### ISSUE TITLE
Add DNS over HTTPS/TLS or custom DNS Provider

### ISSUE THREAD

**Issue by lepz0r** [krlvm/PowerTunnel-Android#1]
Because it's useless on ISPs with DNS redirect or add custom DNS Provider so we can use local DNS Provider like dnscrypt-proxy with termux

**Comment by krlvm** [comment]
I have already started working on it.
At the moment you can just disable custom DNS provider mode and set your dnscrypt-proxy DNS server in the system settings.

**Comment by krlvm** [comment]
DNS over HTTPS mode added in [PowerTunnel v1.10](https://github.com/krlvm/PowerTunnel/releases/tag/v1.10) desktop version

**Comment by krlvm** [comment]
Added in [v1.1 release](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.1)

**Comment by krlvm** [comment]
You're now able to [specify your own DNS provider address](https://github.com/krlvm/PowerTunnel-Android/commit/b9f9a2390a5b334fb534d75763d36bc001bf7e7f).
