### ISSUE TITLE
[Discussion] why some web still blocked?

### ISSUE THREAD

**Issue by NSTAdventure** [krlvm/PowerTunnel-Android#104]
description:
i know PowerTunnel VPN able to bypass cencorship from goverment 

problem:
i want to access reddit that are banned in indonesia country since PowerTunnel VPN able to bypass goverkent cencorship it's really confusing why i still can't access reddit
how i can access the reddit now?

solution:
???

Devices: Realme 5i
Os: ColorOS Based on Android 10 Realme UI 1.0
Devices isn't rooted
Connected using WiFi (Telkomsel)

**Comment by krlvm** [comment]
Hello,

PowerTunnel is a local proxy server which uses Deep Packet Inspection (DPI) systems bugs or limitations to trick them and unblock the websites which previously were unavailable. Thus, it depends on the DPI which your Internet Service Provider is using.

Are you able to connect to an unblocked site (e.g. a government website) when PowerTunnel is running?
If yes, PowerTunnel itself is running correctly, and you need to adjust HTTPS DPI circumvention settings to make it work. At the moment, there are few of them available and they work with _almost_ all providers. If the default configuration does not work, you can try to enable SNI Modification, but it may break websites which is not banned, so you may provide a list of government-blocked resources to make it work more correct.

**Comment by NSTAdventure** [comment]
> Are you able to connect to an unblocked site (e.g. a government website) when PowerTunnel is running?

i said no :-(

> problem:
> i want to access reddit that are banned in indonesia country since PowerTunnel VPN able to bypass goverkent cencorship it's really confusing why i still can't access reddit
> how i can access the reddit now?

**Comment by krlvm** [comment]
Will the [previous version](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.9.1) work?

**Comment by NSTAdventure** [comment]
> Will the [previous version](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.9.1) work?

i will test them ASAP thanks admin 🙏😊

note:
i temporarily close this untill next discussion opened 🙏

**Comment by krlvm** [comment]
Have you tried enabling SNI Modification?

**Comment by NSTAdventure** [comment]
> Have you tried enabling SNI Modification?

not yet in fact i don't know how to enable it? can you show me how to enable SNI modification?

🙏😊

**Comment by krlvm** [comment]
In version 2.0, go to plugins page and open LibertyTunnel settings,  it will be at the bottom

**Comment by NSTAdventure** [comment]
> In version 2.0, go to plugins page and open LibertyTunnel settings, it will be at the bottom

yep tested but still not able to bypass cencorship

i trying again with different app (RDNS) and it worl very well

(but don't get me wrong i just share info not want to compare or anything uncomfortable to everyone)

**Comment by krlvm** [comment]
> i trying again with different app (RDNS) and it worl very well

That means that your provider uses DNS-based filtration actually, which is much easier to bypass, you just need to go to DNS settings and select any provider to make it work.

**Comment by krlvm** [comment]
This can be done via DNS plugin settings, on recent Android versions you don't even need PowerTunnel or any other app for this (https://www.androidpolice.com/2020/03/26/make-android-use-dns-server-choice/)
