### ISSUE TITLE
Нужна возможность отключения моргания светодиодом.

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel-Android#11]
Нужна возможность отключения моргания светодиодом (либо вообще убрать подобную фичу, имхо). 

У меня оба смарта со светодиодами и на одном смарте PowerTunnel после старта прокси моргает синим, а на другом зелёным цветом. Моргать будет продолжать, пока не залезешь в панель уведомлений.

**Comment by krlvm** [comment]
Это настраивается в ОС Android, у некоторых вендоров светодиод будет мигать, пока вы не обратите внимание на непрочитанные уведомления. Это никак не относится к приложению.

**Comment by krlvm** [comment]
Действительно, нет никакой необходимости в "большом" уведомлении о работе прокси, я выставлю ему низший приоритет, возможно, это решит проблему.

**Comment by krlvm** [comment]
Ожидается в [версии 1.5](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.5).

**Comment by Baltazar500** [comment]
Обновил до 1.5 на смарте с 5.1 и 4.2, сделал сброс настроек приложения, но моргать светодиодом он не перестал. Я могу ошибаться, но другие приложения обычно моргали диодом, когда включается режим локального VPN'a. PowerTunnel же моргает даже при включении прокси.

**Comment by krlvm** [comment]
Диод заставляет мигать не приложение, а система Android. Измените приоритет уведомлений PowerTunnel, или вообще их отключите:
![Screenshot_1589437065](https://user-images.githubusercontent.com/51774833/81899633-fc2a1880-95c3-11ea-9efc-69ee78e3c4d1.png)
![Screenshot_1589437070](https://user-images.githubusercontent.com/51774833/81899639-ff250900-95c3-11ea-9d78-5978b8803c1d.png)

**Comment by Baltazar500** [comment]
А, имелось ввиду на корню его уведомления через функционал отключать. На 5.1 проблем не возникло, а на 4.2 такой трюк не прошёл т.к. там нет такой фичи. 

p.s. В принципе мне пришло мне в голову таким образом деактивировать уведомление т.к. вроде без него lowmemorykiller быстрее приложение хлопнет (у меня хром частенько всё выжирает и приложения выносятся одно за другим, а те что в панели уведомлений в последнюю очередь).
