### ISSUE TITLE
Does not work with Adaway

### ISSUE THREAD

**Issue by mirchisait** [krlvm/PowerTunnel-Android#110]
ROM - crDroid A12
Version: 2.1
Magisk with systemless hosts enabled

Hi!

I always get an error, ERR_TIMED_OUT in bromite & other apps won't connect when I use Adaway.

The app works without any issues when I disable Adway & reset the hosts file to default.

**Comment by krlvm** [comment]
You need to exclude PowerTunnel from Adaway proxying and vice versa, like this: https://github.com/krlvm/PowerTunnel-Android/issues/36

Tell if you need additional help.

**Comment by mirchisait** [comment]
There's no option to whitelist or exclude an app in Adaway. All I can do is add hostnames to the whitelist.

**Comment by krlvm** [comment]
Do you use AdAway in VPN mode?

![Screenshot_1643711482 (Среднее)](https://user-images.githubusercontent.com/51774833/151953119-19620617-5902-455c-abb4-8345b22f754f.png) ![Screenshot_1643711537 (Среднее)](https://user-images.githubusercontent.com/51774833/151953115-6241a58b-8d19-4137-9ec9-a020cc6ef206.png)

**Comment by mirchisait** [comment]
I use Adaway in root mode with systemless hosts. 1.9.1 works without any issues even with Adaway enabled.

**Comment by krlvm** [comment]
I don't think it is possible because all Internet traffic goes firstly to AdAway, then to PowerTunnel, then it returns to AdAway and so on ad infinitum :(

**Comment by mirchisait** [comment]
@krlvm I'm using a custom ad-blocking DNS now & it works flawlessly in ver 2.1, & this eliminates the need for using Adaway. Thank you for all your efforts.

**Comment by krlvm** [comment]
You can also use AdBlocker integrated in PowerTunnel with [Firewall plugin](https://github.com/krlvm/PowerTunnel-Firewall) - download *-Android.jar file from Releases and install it via plugin manager. Then you can open PowerTunnel settings and enable option at the bottom, which allows you to save configuration files in Documents directory - after that, run PowerTunnel once, open your File Manager and you will see "configs" directory in Documents/PowerTunnel, where `firewall-hosts.txt` located. After you fill the file, change filtration mode from Proxy to DNS in Firewall plugin settings and you will get the same effect without using another application.

**Comment by mirchisait** [comment]
Hey @krlvm Is there a particular format & hosts type that needs to be entered in the firewall-hosts.txt? For example, if I want to use multiple hosts, should I enter the URLs in separate lines? Also, when I use this https://raw.githubusercontent.com/nickspaargaren/no-google/master/google-domains, nothing gets blocked. I'm a little confused here.

**Comment by krlvm** [comment]
> Hey @krlvm Is there a particular format & hosts type that needs to be entered in the firewall-hosts.txt? For example, if I want to use multiple hosts, should I enter the URLs in separate lines? Also, when I use this https://raw.githubusercontent.com/nickspaargaren/no-google/master/google-domains, nothing gets blocked. I'm a little confused here.

Firewall plugin accepts something like:
```
google.com
github.com
```
