### ISSUE TITLE
connection is not private 🗿

### ISSUE THREAD

**Issue by NSTAdventure** [krlvm/PowerTunnel-Android#114]
and now when power tunnel is active my browser always refuse to connect

because connection is not private
what a nice problem guys
🤙🗿🤙🗿

[powertunnel.log.txt](https://github.com/krlvm/PowerTunnel-Android/files/8238894/powertunnel.log.txt)

log should contain mandatory information
(included All plugin info + config)
to help developer fix issues
if anything miss let me know
thanks 🙏😊

Version: 2.3.1

**Comment by krlvm** [comment]
Looks like you enabled SNI modification and did not install certificate.

**Comment by NSTAdventure** [comment]
> Looks like you enabled SNI modification and did not install certificate.

![Screenshot_2022-03-13-16-05-31-57](https://user-images.githubusercontent.com/50813528/158052669-61cf1923-4c90-435a-9483-058c656413af.jpg)
 ?????????

**Comment by krlvm** [comment]
Clear your browser cache, so it will allow to load the page with a different certificate or try to install another browser.
You can also limit the scope of the websites where SNI modification is applied.
