### ISSUE TITLE
dns mode to bypass cencorship?

### ISSUE THREAD

**Issue by NSTAdventure** [krlvm/PowerTunnel-Android#115]
hi dev pls considering add dns mode if not exist yet

RDNS app using this method to bypass cencorship

disclaimer:
actually this is are Discussion not issues but discussion tab has been disabled here

**Comment by krlvm** [comment]
I can't find the app you are talking about.
PowerTunnel already has a DNS module.

**Comment by NSTAdventure** [comment]
> I can't find the app you are talking about.

https://www.rethinkdns.com/

i mean this app sir
I've also mention this on previous issues

**Comment by krlvm** [comment]
The only option related to block bypass in RethinkDNS is DNS over HTTPS, which is already supported.

Go to plugins, open DNS plugin settings and select Google DoH or Cloudflare DoH profile to achieve the same effect.

**Comment by NSTAdventure** [comment]
> The only option related to block bypass in RethinkDNS is DNS over HTTPS, which is already supported.
> 
> Go to plugins, open DNS plugin settings and select Google DoH or Cloudflare DoH profile to achieve the same effect.

i have 1 question left
is that possible to use multiple DOH on this power tunnel app? 
if yes can you implement that feature?

thanks for your time sir 
🙏😄😄😄😄

**Comment by krlvm** [comment]
You can't and don't need to use multiple DNS resolvers.

https://en.wikipedia.org/wiki/Domain_Name_System
https://en.wikipedia.org/wiki/DNS_over_HTTPS
