### ISSUE TITLE
Для прокси нужна возможность регулировать ip и порт.

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel-Android#12]
Для прокси нужна возможность регулировать ip и порт.

С портом на случай, если окажется занят, а ip на cлучай использования ProxyTunnel'я на смарте/плеере и т.д. как средства обхода блокировки другими устройствами (т.е. слушать 0.0.0.0 вместо 127.0.0.1). В последнем случае возможность поднять порт "повыше" при любом раскладе была бы не лишней :)

**Comment by krlvm** [comment]
Ожидается в [версии 1.5](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.5).
