### ISSUE TITLE
Support for F-Droid/Aurora Store

### ISSUE THREAD

**Issue by dtantono** [krlvm/PowerTunnel-Android#126]
Hi
I know Play Store release violate DMCA and I know there was F-Droid request in the past (https://github.com/krlvm/PowerTunnel-Android/issues/2). But, it does not show up in F-droid repository. So,, Is it possible to support F-Droid/Aurora Store?

**Comment by krlvm** [comment]
Publishing to F-Droid is not possible due to the plugin system, i.e. support for sideloading jar files, but is it available on IzzyOnDroid F-Droid repository: https://apt.izzysoft.de/fdroid/
