### ISSUE TITLE
Возникает дубликат окна после старта PowerTunnel, его сворачивания и вызова из панели уведомлений.

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel-Android#13]
После старта PowerTunnel, его сворачивания и вызова из панели уведомлений и последующем нажатии софт-тач кнопки "назад" видно, что сворачивается дубль окна, повторное нажатие кнопки сворачивает программу окончательно. 

Благо дубликат всего один. 

Недавно в другом приложении словил подобное и там дубликаты плодились каждый раз при открытии приложения из панели уведомлений. Поэтому тут глаз и зацепился за аналогичную оказию.

**Comment by Baltazar500** [comment]
Ещё идёт расколбас с дубликатами, если заходить в настройки и сворачивать, заходить и сворачивать ...

Кнопка "назад" потом все эти дубли начинает закрывать - окно приложения, окно настроек и т.д.

**Comment by krlvm** [comment]
Ожидается в [версии 1.5](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.5).
