### ISSUE TITLE
Cannot make dns resolver work in vpn mode

### ISSUE THREAD

**Issue by Maythemo** [krlvm/PowerTunnel-Android#131]
Dns resolver not working vpn mode with only 3 apps included
not working with DOH server
or even personaldnsfilter with 127.0.01:5300

Can dns resolver resplve all requests in android device for whole device and apps?

**Comment by krlvm** [comment]
Which Android version you are using?

To make it work with personalDNSFilter, exclude it from proxying.

**Comment by Maythemo** [comment]
its Android 9
I set https://fqdn:52341(portnumber)/dns-query in DNS resolver but there is no query log on my DNS server.
Then I set it to 127.0.01:5300  again no luck.
I am on VPN mode with pDNSf excluded in powertunel

Does the Private DNS in android setting affect st. in OFF and Auto setting.

**Comment by krlvm** [comment]
Are you sure custom DNS resolver is disabled in your browser settings?
Check PowerTunnel logs to make sure there is no errors on client side.

**Comment by Maythemo** [comment]
maybe related to this
#73 
I am using upstream proxy

**Comment by krlvm** [comment]
If you are using an upstream proxy, your DNS requests are handled by it, not by PowerTunnel.

**Comment by Maythemo** [comment]
I am using HTTP/HTTPS is it true for this type?
If I vpn my whole device, does all traffic including DNS goes through upstream proxy?
or only HTTP and HTTPS?

**Comment by krlvm** [comment]
The DNS requests are being processed by your upstream proxy in this case.
