### ISSUE TITLE
Can't Load Plugin .jar

### ISSUE THREAD

**Issue by DionGanteng** [krlvm/PowerTunnel-Android#133]
I'm trying to reduce app size with proguard by enabling
minifyEnabled true
shrinkResources true

I couldn't find any proguard setup documentation for this app and its plugins. I hope you can help

**Comment by krlvm** [comment]
It would be possible to completely exclude the `io.github.krlvm.powertunnel` package from obfuscation, but I'm not sure if that would work.

Theoretically, plugins can access not only the PowerTunnel API, but also the libraries on which it depends, including pulling LittleProxy internal APIs, so I do not plan to do anything to support ProGuard at the moment.

**Comment by DionGanteng** [comment]
I've tried excluding anything but excluding io.github.krlvm.powertunnel. But the app still crashes.
Thanks for the reply
