### ISSUE TITLE
Using adblock plugin crashes the app

### ISSUE THREAD

**Issue by katyusha128** [krlvm/PowerTunnel-Android#139]
It still crashes even if only adblock is checked
I'm on the latest version and got this log
` --------- beginning of crash
01-31 12:00:44.301 25011 25011 E AndroidRuntime: FATAL EXCEPTION: main
01-31 12:00:44.301 25011 25011 E AndroidRuntime: Process: io.github.krlvm.powertunnel.android, PID: 25011
01-31 12:00:44.301 25011 25011 E AndroidRuntime: android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{15af02b u0 io.github.krlvm.powertunnel.android/.services.TunnelingVpnService}
01-31 12:00:44.301 25011 25011 E AndroidRuntime: 	at android.app.ActivityThread.throwRemoteServiceException(Unknown Source:11)
01-31 12:00:44.301 25011 25011 E AndroidRuntime: 	at android.app.ActivityThread.access$2800(Unknown Source:0)
01-31 12:00:44.301 25011 25011 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(Unknown Source:387)
01-31 12:00:44.301 25011 25011 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Unknown Source:19)
01-31 12:00:44.301 25011 25011 E AndroidRuntime: 	at android.os.Looper.loopOnce(Unknown Source:176)
01-31 12:00:44.301 25011 25011 E AndroidRuntime: 	at android.os.Looper.loop(Unknown Source:76)
01-31 12:00:44.301 25011 25011 E AndroidRuntime: 	at android.app.ActivityThread.main(Unknown Source:138)
01-31 12:00:44.301 25011 25011 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-31 12:00:44.301 25011 25011 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
01-31 12:00:44.301 25011 25011 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(Unknown Source:309)
01-31 12:00:44.307 25011 25011 W OOMEventManagerFK: Failed to mkdir /data/mqsas/hprof/
01-31 12:00:45.625 25341 25341 I ForceDarkHelperStubImpl: initialize for io.github.krlvm.powertunnel.android , ForceDarkOrigin
`

**Comment by krlvm** [comment]
I remember this crash has been around for quite some time, it is not related to plugins, but to managing the state of the VPN service (#120).

Try to connect again, it should not crash anymore, the AdBlock plugin has nothing to do with it :/.
