### ISSUE TITLE
Деактивация опций "способ соединения", "исключённые" и "разрешённые приложения" при переключении на режим прокси ?

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel-Android#14]
Имхо, имеет смысл деактивировать опции "способ соединения", "исключённые" и "разрешённые приложения" при переключении на режим прокси.

**Comment by krlvm** [comment]
Они все равно не будут оказывать никакого влияния на работу приложения в режиме прокси, но я согласен, что визуально их следует отключить.

**Comment by krlvm** [comment]
Ожидается в [версии 1.5](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.5).
