### ISSUE TITLE
Additional for plugin functions

### ISSUE THREAD

**Issue by GuckTubeYT** [krlvm/PowerTunnel-Android#142]
Is it possible to make file reader on Plugin? is it possible, how do i make file reader on Plugin?

**Comment by krlvm** [comment]
Yes, standard interfaces are fully available to you, and you can call `readTextFile` from your plugin's main class to read any file in `configs` directory, like it is used [here](https://github.com/krlvm/LibertyTunnel/blob/master/src/main/java/io/github/krlvm/powertunnel/plugins/libertytunnel/LibertyTunnel.java).

Didn't really think of a way to obtain configuration directory at runtime, I will add a method for that in the next version, you can just hardcode it at the moment.

**Comment by GuckTubeYT** [comment]
> Yes, standard interfaces are fully available to you, and you can call `readTextFile` from your plugin's main class to read any file in `configs` directory, like it is used [here](https://github.com/krlvm/LibertyTunnel/blob/master/src/main/java/io/github/krlvm/powertunnel/plugins/libertytunnel/LibertyTunnel.java).
> 
> Didn't really think of a way to obtain configuration directory at runtime, I will add a method for that in the next version, you can just hardcode it at the moment.

oh okay okay thanks, and, can you make Error Messagebox for Plugins please

**Comment by GuckTubeYT** [comment]
example, if user didnt put anything at require user input, it will show error messagebox on android, or when user press start button, the app wil show error message

**Comment by GuckTubeYT** [comment]
> Yes, standard interfaces are fully available to you, and you can call `readTextFile` from your plugin's main class to read any file in `configs` directory, like it is used [here](https://github.com/krlvm/LibertyTunnel/blob/master/src/main/java/io/github/krlvm/powertunnel/plugins/libertytunnel/LibertyTunnel.java).
> 
> Didn't really think of a way to obtain configuration directory at runtime, I will add a method for that in the next version, you can just hardcode it at the moment.

oh yeah, btw, i mean like file user interface, so user can select the file

**Comment by GuckTubeYT** [comment]
> You can throw an exception and its message will be shown to user
Sorry, can you make the example code?

Thanks

**Comment by krlvm** [comment]
```java
public class MyPlugin extends PowerTunnelPlugin {

    @Override
    public void onProxyInitialization(@NotNull ProxyServer proxy) {
        // ...
        if (somethingIsWrong) {
            throw new Exception("Error message");
        }
        // ...
    }

}
```

**Comment by GuckTubeYT** [comment]
ohh okay okay, and it will show the dialog error?

**Comment by GuckTubeYT** [comment]
okay okay thanks
