### ISSUE TITLE
Поддержка intercepted proxy ?

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel-Android#15]
Попробовал через iptables перенаправить запросы конкретного приложения (браузера) на прокси

>iptables -t nat -I OUTPUT -p tcp --dport 80 -m owner --uid-owner 10189 -m tcp -j REDIRECT --to-ports 8085
>iptables -t nat -I OUTPUT -p tcp --dport 443 -m owner --uid-owner 10189 -m tcp -j REDIRECT --to-ports 8085

но похоже прокси не работает в intercepted-режиме :

>Bad Request to URI: /

**Comment by krlvm** [comment]
Это особенность LittleProxy, который используется в качестве прокси-сервера.
У меня есть возможное [решение](https://github.com/krlvm/PowerTunnel-Android/files/4608764/PowerTunnel-v1.4-fix-compat.zip) (APK совместим с Android 4.2) этой проблемы, я включу его в основную ветку разработки, если вы подтвердите его работоспособность.

**Comment by Baltazar500** [comment]
Под рукой был смарт с 5.1 - проверил на нём. Для http (80) сработало, а для https трюк не прошёл (хотя это по моему у меня и ранее не срабатывало для другого софта). По крайней мере фокс для https выдаёт вот такой алерт :

>An error occurred during a connection to rutracker.org. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG

**Comment by krlvm** [comment]
Исправлено в [версии 1.5.1](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.5.1), исправление портировано из PowerTunnel v1.11.
