### ISSUE TITLE
SNI Bug: A large number of websites are inaccessible

### ISSUE THREAD

**Issue by Pantyhose-X** [krlvm/PowerTunnel-Android#167]
![Screenshot_20240322-075413](https://github.com/krlvm/PowerTunnel-Android/assets/42504385/f9e56289-dc8e-4efd-952c-fccf2bd11d3c)
![Screenshot_20240322-075419](https://github.com/krlvm/PowerTunnel-Android/assets/42504385/ef3ed149-169d-4fa4-9730-7799efa22989)
![Screenshot_20240322-075443](https://github.com/krlvm/PowerTunnel-Android/assets/42504385/3baea400-1138-47b2-b545-b6493577ec63)

**Comment by krlvm** [comment]
It's not a bug, read the docs
