### ISSUE TITLE
Custom DNS Port

### ISSUE THREAD

**Issue by arasyi** [krlvm/PowerTunnel-Android#17]
My ISP captures port 53, is it possible to specify alternate port for the DNS?

**Comment by krlvm** [comment]
At the moment you can specify alternate port if you have an IPv6 DNS address: `[ipv6]:port`

**Comment by krlvm** [comment]
Available in [version 1.5.2](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.5.2)
