### ISSUE TITLE
The problem with YouTube in Russia

### ISSUE THREAD

**Issue by Empty3346** [krlvm/PowerTunnel-Android#172]
YouTube in Russia is being slowed down by providers. GoodbyeDPI 0.2.3 is successful at coping with this on Windows, but Power Tunnel on Android does not help from slowing down. Is it possible to fix this using the settings?

**Comment by krlvm** [comment]
Зависит от провайдера, попробуйте https://github.com/dovecoteescapee/ByeDPIAndroid

**Comment by Empty3346** [comment]
> Зависит от провайдера, попробуйте https://github.com/dovecoteescapee/ByeDPIAndroid

У меня Ростелеком. Попропую ByeDPI, спасибо.

**Comment by Empty3346** [comment]
> Зависит от провайдера, попробуйте https://github.com/dovecoteescapee/ByeDPIAndroid

К сожалению, ByeDPI тоже не помогает с замедлением. Вроде получше становится, но совсем чуть-чуть.

**Comment by krlvm** [comment]
Эти программы либо работают, либо не работают совсем - попробуйте поиграться с опциями ByeDPI

**Comment by Empty3346** [comment]
> Эти программы либо работают, либо не работают совсем - попробуйте поиграться с опциями ByeDPI

Значит показалось. А с какими опциямм поиграться стоит? Их там много, я поди только поломаю всё)

**Comment by krlvm** [comment]
У меня вроде бы все работает с Desync=Fake из ByeDPI в одной сети, и просто со Split TLS Record, включенным в PT по умолчанию, в другой

**Comment by Empty3346** [comment]
> У меня вроде бы все работает с Desync=Fake из ByeDPI в одной сети, и просто со Split TLS Record, включенным в PT по умолчанию, в другой

Попробовал покрутить разные настройки в BD, включая эти — не помогает.

**Comment by Fuwiz** [comment]
> > У меня вроде бы все работает с Desync=Fake из ByeDPI в одной сети, и просто со Split TLS Record, включенным в PT по умолчанию, в другой
> 
> Попробовал покрутить разные настройки в BD, включая эти — не помогает.

![image](https://github.com/user-attachments/assets/5c6ef1d9-5338-47c7-a3e5-7aa74af33ca3)

Попробуй вот эту настройку изменить. У меня с дефолтной 3 не работало, а с 1 или 2 работает

**Comment by Empty3346** [comment]
> > > У меня вроде бы все работает с Desync=Fake из ByeDPI в одной сети, и просто со Split TLS Record, включенным в PT по умолчанию, в другой
> > 
> > 
> > Попробовал покрутить разные настройки в BD, включая эти — не помогает.
> 
> ![image](https://private-user-images.githubusercontent.com/62134155/356433226-5c6ef1d9-5338-47c7-a3e5-7aa74af33ca3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxODg5NzIsIm5iZiI6MTcyMzE4ODY3MiwicGF0aCI6Ii82MjEzNDE1NS8zNTY0MzMyMjYtNWM2ZWYxZDktNTMzOC00N2M3LWEzZTUtN2FhNzRhZjMzY2EzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA3MzExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ODdmYjBkMDA0ZTgxODg4NTU1MjdlNWY0ODAwZTJhYzA5ZWUwNTlkNTUwZGQzNDcwZjYwZTU5ODBmYTdmZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HkVvcHjAU_FOc77F2s2Ms0Tjl28ElpIo9lDNHCuY7DY)
> 
> Попробуй вот эту настройку изменить. У меня с дефолтной 3 не работало, а с 1 или 2 работает

Пробовал уже — бесполезно(
