### ISSUE TITLE
Publish the app in the central F-Droid repository

### ISSUE THREAD

**Issue by methuselahin** [krlvm/PowerTunnel-Android#19]
https://f-droid.org/ Please upload your app here. So that we can keep track of updates instead of opening github all the time.

**Comment by krlvm** [comment]
Hello, PowerTunnel is already published on F-Droid (#2), but it seems to be not in the main repository, I'll check.
You do not have to open GitHub all the time, you automatically receive a notification in the app when an update is available.

**Comment by methuselahin** [comment]
thanks 😊

**Comment by krlvm** [comment]
I've [requested](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7018) publishing to the main repository, it should be available within a few days.

**Comment by methuselahin** [comment]
> I've [requested](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7018) publishing to the main repository, it should be available within a few days.

wonderful bro. thanks for quick response
