### ISSUE TITLE
Stopped working today, YouTube, Android 12, TTK

### ISSUE THREAD

**Issue by SergeVDev** [krlvm/PowerTunnel-Android#195]
The latest version has stopped working with TTK today. Android 12, youtube.com in Firefox for Android.

I can attach a log, if the app creates any.

**Comment by etadex** [comment]
I confirm, stopped working on Dom.ru provider too. If there are some settings someone can provide for LibertyTunnel plugin or some advice, I would greatly appreciate it.

upd: GoodbyeDPI 0.2.3rc with "-1" profile on PC still works. I wonder if someone can elaborate on how to use the settings from it in LibertyTunnel.

**Comment by krlvm** [comment]
> upd: GoodbyeDPI 0.2.3rc with "-1" profile on PC still works. I wonder if someone can elaborate on how to use the settings from it in LibertyTunnel.

Первый режим эквивалентен дефолтным настройкам LibertyTunnel
