### ISSUE TITLE
Не работает или низкая скорость

### ISSUE THREAD

**Issue by DKStern** [krlvm/PowerTunnel-Android#197]
Вот уже пару дней невозможно смотреть ютуб на телефонах. Прогружает только список видео и их картинки, а сами видео не грузятся. Точнее грузятся очень медленно, за 10 минут ожидания прогрузилось всего пару секунд. Такая ситуация на всех телефонах в семье, на разных мобильных операторах. Версия последняя.

Логи:
[powertunnel.log.txt](https://github.com/user-attachments/files/17202421/powertunnel.log.txt)

**Comment by kpandroid** [comment]
Дядя, ты дурак? Это просто приложение, оно скорость твою не меняет, пиши в РКН, это они тормозят Ютуб..

**Comment by DKStern** [comment]
> Дядя, ты дурак? Это просто приложение, оно скорость твою не меняет, пиши в РКН, это они тормозят Ютуб.

Если ничего умного написать не можешь, лучше не пиши. Первая же строчка описания "The Android version of PowerTunnel is built on top of incredible NetGuard's VPN Server that intercepts traffic and directs it through the local PowerTunnel proxy", а VPN скорость режет.
До этого нормально всё обходило ограничения РКН, сейчас же перестало. Без PowerTunnel ютуб вообще не грузится, а с ним сейчас грузится только список видео, но не сами видео, хотя должно грузится всё.

**Comment by kpandroid** [comment]
Это не VPN, а туннель, он не изменяет твой скорости, хотяб почитай, что установил :) РКН замедляет тебе Ютуб - пиши им, они в курсе и это именно они блокируют приложение, т.к. у них миллиардные бюджеты на цензуру.

**Comment by CobaltonGit** [comment]
> Это не VPN, а туннель, он не изменяет твой скорости, хотяб почитай, что установил :) РКН замедляет тебе Ютуб - пиши им, они в курсе и это именно они блокируют приложение, т.к. у них миллиардные бюджеты на цензуру.

ркн не читает жалобы, умник

**Comment by kpandroid** [comment]
> ркн не читает жалобы

тогда давай, сюда наваливать

**Comment by Dronatar** [comment]
> Если ничего умного написать не можешь, лучше не пиши. Первая же строчка описания "The Android version of PowerTunnel is built on top of incredible NetGuard's VPN Server that intercepts traffic and directs it through the local PowerTunnel proxy", а VPN скорость режет. До этого нормально всё обходило ограничения РКН, сейчас же перестало. Без PowerTunnel ютуб вообще не грузится, а с ним сейчас грузится только список видео, но не сами видео, хотя должно грузится всё.

Если это сообщение было написано не под наркотическим эффектом, то перед тем как писать подобные сообщения со своего аккаунта в публичный интернет с историей, лучшей узнай что такое [NetGuard](https://github.com/M66B/NetGuard)'s VPN Server и как он используется в этом приложении. Так же если не скуф, то советую прочитать более трех строк про PowerTunnel, там аж для детей расписано про твою ошибку.
