### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [krlvm/PowerTunnel-Android#2]
Hi @krlvm 

Since this app is MIT licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

**Comment by krlvm** [comment]
I see no reason against it, I will do it within a week.

**Comment by Poussinou** [comment]
You can start by opening a RFP [here on F-Droid side](https://gitlab.com/fdroid/rfp/issues).

**Comment by krlvm** [comment]
I've left an [issue](https://gitlab.com/fdroid/rfp/-/issues/1265)

**Comment by IzzySoft** [comment]
Until that RFP is processed and your app available at f-droid.org, you can already [find it in my repo](https://apt.izzysoft.de/fdroid/index/apk/ru.krlvm.powertunnel.android). May I suggest you establish [Fastlane file structure](https://gitlab.com/snippets/1895688) here, so F-Droid can pick description, screenshots etc from it while you can update it whenever needed? That way you wouldn't need to open a merge request each time you want something changed in the description (or provide newer/additional screenshots).

**Comment by krlvm** [comment]
> Until that RFP is processed and your app available at f-droid.org, you can already [find it in my repo](https://apt.izzysoft.de/fdroid/index/apk/ru.krlvm.powertunnel.android). May I suggest you establish [Fastlane file structure](https://gitlab.com/snippets/1895688) here, so F-Droid can pick description, screenshots etc from it while you can update it whenever needed? That way you wouldn't need to open a merge request each time you want something changed in the description (or provide newer/additional screenshots).

Have done

**Comment by IzzySoft** [comment]
@krlvm Thanks! Can you please cover that by a tag? Untagged Fastlane isn't picked up (everything is picked up from the tag, so description matches version).

**Comment by krlvm** [comment]
> @krlvm Thanks! Can you please cover that by a tag? Untagged Fastlane isn't picked up (everything is picked up from the tag, so description matches version).
> 
> PS: FeatureGraphic should have proportions 2:1 (rectangle, not square).

Sorry for inconvenience, what's the tag?

**Comment by IzzySoft** [comment]
[Tagged releases](https://github.com/krlvm/PowerTunnel-Android/releases)? :wink:

**Comment by krlvm** [comment]
> [Tagged releases](https://github.com/krlvm/PowerTunnel-Android/releases)? 😉

I was just planning on making a new release today.

**Comment by IzzySoft** [comment]
Perfect! Then we wait for that (even if it comes tomorrow). Just ping me when it's there, so I prepare metadata and push your RFP "upstairs" to our packagers. Thanks!

**Comment by krlvm** [comment]
> Perfect! Then we wait for that (even if it comes tomorrow). Just ping me when it's there, so I prepare metadata and push your RFP "upstairs" to our packagers. Thanks!

I have released tag [v1.1](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.1)

**Comment by IzzySoft** [comment]
Thanks! I've setup metadata in the RFP and send the "ready" signal to our packagers. :crossed_fingers:

**Comment by krlvm** [comment]
> Thanks! I've setup metadata in the RFP and send the "ready" signal to our packagers. 🤞

Thank you
