### ISSUE TITLE
Can you add a button to the status bar?

### ISSUE THREAD

**Issue by kimpig** [krlvm/PowerTunnel-Android#33]
Hi
This app is really convenient, but it doesn't have the button to turn it on and off from the status bar like Intra.  Can you add it?

**Comment by krlvm** [comment]
You can try to disconnect VPN using system's VPN dialog.

**Comment by kimpig** [comment]
That's right. but if I want to reconnect, I should go to app and touch start button. So I think How about make button on status bar(called quick panel?)

![20201017_120433](https://user-images.githubusercontent.com/61234733/96327044-f3f17000-1070-11eb-84a7-bb7e27a623ab.jpg)

**Comment by krlvm** [comment]
Very good idea, I will do it in the next version

**Comment by krlvm** [comment]
Available in [version 1.8](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.8), please, write does it work properly on your device.

**Comment by kimpig** [comment]
Thanks for the quick update.  By the way, the button is visible, but when pressed, the app is forcibly closed and it does not work...

![Screenshot_20201018-103659_Samsung Experience Home](https://user-images.githubusercontent.com/61234733/96356737-0da4bd00-112e-11eb-9d10-9d458d3eba03.jpg)

**Comment by krlvm** [comment]
You have to enable and disable PowerTunnel from app at the first, in the future everything works without problems, I'm going to release a fix for this issue.
Waiting for your reply.

**Comment by kimpig** [comment]
If I enter the app and turn it on and off, The button on quick bar works, but if I try to reconnect in the quick bar,  same error ocurred

**Comment by krlvm** [comment]
I noticed that this issue solves after reinstalling the app, uninstall PowerTunnel and install [a new version](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.8.1).
Waiting for your reply.

**Comment by kimpig** [comment]
It works very well. Thank you! But to tell you one thing, if I turn on PowerTunnel after I used another vpn app, even if it's not my first time using it, I get an error message. I think it'll be better if this part is solved!

**Comment by krlvm** [comment]
> It works very well. Thank you! But to tell you one thing, if I turn on PowerTunnel after I used another vpn app, even if it's not my first time using it, I get an error message. I think it'll be better if this part is solved!

Unfortunately, I do not have a lot of time for fixing subtleties like that, but I always welcome Pull Requests if you can fix it.
Thank you for the amazing idea about Quick Tile!

**Comment by krlvm** [comment]
> It works very well. Thank you! But to tell you one thing, if I turn on PowerTunnel after I used another vpn app, even if it's not my first time using it, I get an error message. I think it'll be better if this part is solved!

I decided to fix it and pushed a fix with [version 1.8.2](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.8.2), does it fixed the issue for you?
