### ISSUE TITLE
Allow to start proxy on boot

### ISSUE THREAD

**Issue by Navneet-Suresh** [krlvm/PowerTunnel-Android#35]
Hi, First I want to thank you for making this tool available on Android, recently Indian ISP's have increased censorship efforts and block websites randomly, [archive.org](https://www.medianama.com/2017/08/223-internet-archive-blocked-court-orders-obtained-bollywood-studios/), [wetransfer](https://indianexpress.com/article/technology/tech-news-technology/india-blocks-wetransfer-6437543/) etc using DPI and this tool has made the web accessible again.

Anyways I use PowerTunnel with [Blokada](https://blokada.org/index.html) (Custom DNS and Filtering ads). Every time the device is rebooted, I loose internet connection as I have setup proxy for my Wi-Fi connection, it would be amazing if you would consider adding an autostart function.

Regards,

**Comment by krlvm** [comment]
It's already available AFAIK, just don't disable PowerTunnel before shutdown.

**Comment by Navneet-Suresh** [comment]
> It's already available AFAIK, just don't disable PowerTunnel before shutdown.

Oh okay, I have two android devices and both of them have issue with Autostart. I have to manually enable Proxy whenever I restart my device.
Device 1 is One Plus 3T on Android Pie
Device 2 is Motorola One Vision on Android 10.

**Comment by Navneet-Suresh** [comment]
Let me see if I can get logs for you.

**Comment by Navneet-Suresh** [comment]
Logs!

## Attachments

[moto-logcat-19-10-2020.txt](https://github.com/krlvm/PowerTunnel-Android/files/5401201/moto-logcat-19-10-2020.txt)

[OnePlus3T-logcat-19-10-2020.txt](https://github.com/krlvm/PowerTunnel-Android/files/5401198/OnePlus3T-logcat-19-10-2020.txt)

**Comment by krlvm** [comment]
Indeed, I do not see BootReceiver messages in the log. I heard there are some problems with boot broadcast receivers on Android Oreo and higher, especially on OnePlus devices.
I think I should implement [this](https://stackoverflow.com/a/41627296) workaround.
Have you tried to put PowerTunnel in battery optimizer whitelist?

**Comment by Navneet-Suresh** [comment]
On OnePlus, I have disabled battery optimizations for all apps that I use regularly, the issue persists.

**Comment by krlvm** [comment]
I think it depends on phone vendor, I've just rebooted my Samsung Android 10 phone with battery saver enabled, and PowerTunnel have started after a minute after boot.
I'm looking for possible solutions, but I don't think I could properly test them since all is OK on my device.

If you're skilled in Android development and found a workaround for your device let me know (write here or open a Pull Request).

**Comment by Navneet-Suresh** [comment]
Okay, makes sense, some vendors screw the devices with unnecessary "Battery Optimisations". I use Blokada and it works out of the box on both the devices so i will check their source code to see what they are doing.

**Comment by krlvm** [comment]
> Okay, makes sense, some vendors screw the devices with unnecessary "Battery Optimisations". I use Blokada and it works out of the box on both the devices so i will check their source code to see what they are doing.

Thanks for the idea, I looked into their source code and changed my implementation, I think this APK should work: 
[PowerTunnel-v1.8.2-bootfix.zip](https://github.com/krlvm/PowerTunnel-Android/files/5404287/PowerTunnel-v1.8.2-bootfix.zip)

**Comment by Navneet-Suresh** [comment]
> Thanks for the idea, I looked into their source code and changed my implementation, I think this APK should work:
PowerTunnel-v1.8.2-bootfix.zip

Testing it now. 

## Test Devices

- [ ] Moto One Vision

- [ ] OnePlus 3T

**Comment by krlvm** [comment]
Providing logs is optional, because the receiver is simply not called, and I'm trying to understand why :(

**Comment by Navneet-Suresh** [comment]
[PT-Logs.zip](https://github.com/krlvm/PowerTunnel-Android/files/5404473/PT-Logs.zip)

Here you go! Why do manufacturers do this :/
This might be helpfull ?
https://dontkillmyapp.com/

**Comment by krlvm** [comment]
It's appears to be a long-known issue on OnePlus, and unfortunately I haven't found something interested yet, but someone says there's something like Autostart menu in settings, don't you have it?

**Comment by Navneet-Suresh** [comment]
@krlvm can you register a notification service and run it at boot? It will also protect app from getting killed.

**Comment by krlvm** [comment]
> @krlvm can you register a notification service and run it at boot? It will also protect app from getting killed.

As far as I know, a service can't start automatically, so it needs a Boot Receiver to start too.

**Comment by Navneet-Suresh** [comment]
> It's appears to be a long-known issue on OnePlus, and unfortunately I haven't found something interested yet, but someone says there's something like Autostart menu in settings, don't you have it?

Nope, I don't see it. I am sure it must have been a feature in previous oxygen os release.

**Comment by krlvm** [comment]
Isn't the app installed on external storage?

**Comment by Navneet-Suresh** [comment]
> > @krlvm can you register a notification service and run it at boot? It will also protect app from getting killed.
> 
> As far as I know, a service can't start automatically, so it needs a Boot Receiver to start too.

Ok, I understand, lets leave OnePlus for now. I am having same issue with Moto One Vision and it runs Stock Android 10, and is on latest security patch Sept 1 2020.

Is it also having issue with Boot Receiver?

**Comment by Navneet-Suresh** [comment]
> Isn't the app installed on external storage?

OnePlus doesn't have external storage :/ so its on the internal storage.

**Comment by krlvm** [comment]
I found an interesting [solution](https://stackoverflow.com/a/63250729) that uses `android.permission.SYSTEM_ALERT_WINDOW` permission, can you test it?
[PowerTunnel-v1.8.2-bootfix2.zip](https://github.com/krlvm/PowerTunnel-Android/files/5404555/PowerTunnel-v1.8.2-bootfix2.zip)

**Comment by Navneet-Suresh** [comment]
Is this SO question related? https://stackoverflow.com/questions/51221680/broadcast-receiver-not-working-in-android-oreo

**Comment by Navneet-Suresh** [comment]
> I found an interesting [solution](https://stackoverflow.com/a/63250729) that uses `android.permission.SYSTEM_ALERT_WINDOW` permission, can you test it?
> [PowerTunnel-v1.8.2-bootfix2.zip](https://github.com/krlvm/PowerTunnel-Android/files/5404555/PowerTunnel-v1.8.2-bootfix2.zip)

Off course, brb testing it

**Comment by krlvm** [comment]
> Is this SO question related? https://stackoverflow.com/questions/51221680/broadcast-receiver-not-working-in-android-oreo

No, `BOOT_COMPLETED` is still allowed in Oreo and higher

**Comment by Navneet-Suresh** [comment]
> I found an interesting [solution](https://stackoverflow.com/a/63250729) that uses `android.permission.SYSTEM_ALERT_WINDOW` permission, can you test it?
> [PowerTunnel-v1.8.2-bootfix2.zip](https://github.com/krlvm/PowerTunnel-Android/files/5404555/PowerTunnel-v1.8.2-bootfix2.zip)
> 
> _For some reason the app crashes after you grant the permission, but all is fine after you open it again_

Tried the newer version and it also didn't work. I also use revolutionirc and it works fine on bot hdevices and starts at boot.
https://github.com/MCMrARM/revolution-irc

**Comment by krlvm** [comment]
I just noticed you are running PowerTunnel in proxy mode, am I right?

**Comment by Navneet-Suresh** [comment]
Yeah, in proxy mode with Blokada as VPN.

**Comment by krlvm** [comment]
That makes sense. There was only VPN support on boot until now.

**Comment by krlvm** [comment]
This APK has support for proxy start on boot
[PowerTunnel-v1.8.2-bootfix5.zip](https://github.com/krlvm/PowerTunnel-Android/files/5404866/PowerTunnel-v1.8.2-bootfix5.zip)

**Comment by Navneet-Suresh** [comment]
> That makes sense. There is no feature to start proxy after boot.

Oh > . < .. trying the new variant.

**Comment by krlvm** [comment]
Did you start the proxy before reboot? All is working for me.

**Comment by Navneet-Suresh** [comment]
> Did you start the proxy before reboot? All is working for me.

yeah, started the proxy, tested it then rebooted.

**Comment by krlvm** [comment]
Can you share logs? I've made verbose output.

**Comment by Navneet-Suresh** [comment]
> Can you share logs? I've made verbose output.

yes. brb

**Comment by krlvm** [comment]
It's actually started, but was immediately killed by system because I forgot to start the service ¯\_(ツ)_/¯

**Comment by Navneet-Suresh** [comment]
> It's actually started, but was immediately killed by system because I forgot to start the service ¯\_(ツ)_/¯

haha! ಥ_ಥ

**Comment by krlvm** [comment]
Sorry for inconvenience, this start the service [properly](https://github.com/krlvm/PowerTunnel-Android/commit/f79ae1eb76b085754e64d0c4af7660108a496c73)
[PowerTunnel-v1.8.2-bootfix10.zip](https://github.com/krlvm/PowerTunnel-Android/files/5405108/PowerTunnel-v1.8.2-bootfix10.zip)

**Comment by krlvm** [comment]
Tested on two devices, it's works on Android 7 and lower, but don't on Android 8+

**Comment by krlvm** [comment]
It looks like a comedy TBH, but this build finally working on all my devices
[PowerTunnel-v1.8.2-bootfix13.zip](https://github.com/krlvm/PowerTunnel-Android/files/5405172/PowerTunnel-v1.8.2-bootfix13.zip)

**Comment by Navneet-Suresh** [comment]
> Tested on two devices, it's works on Android 7 and lower, but don't on Android 8+

service starts fine on boot, butI was unable to access sites which worked previously. DPI prevention.

Trying your latest build 🤞 ╰(*°▽°*)╯

**Comment by Navneet-Suresh** [comment]
> It looks like a comedy TBH, but this build finally working on all my devices
> [PowerTunnel-v1.8.2-bootfix13.zip](https://github.com/krlvm/PowerTunnel-Android/files/5405172/PowerTunnel-v1.8.2-bootfix13.zip)
> 
> _The proxy becomes available after ~1 minute after boot._

Working fine now. Thanks ^_^

**Comment by krlvm** [comment]
Cool!

I've already released three updates this week, so I think I can push this feature with a next release in the next month.

I have never been so happy when closing an issue ^_^ .

**Comment by Navneet-Suresh** [comment]
Sure, I am glad I could help with the fix ;)
