### ISSUE TITLE
How to setup PowerTunnel to work with AdGuard?

### ISSUE THREAD

**Issue by n0101** [krlvm/PowerTunnel-Android#36]
PowerTunnel v1.8.2
Adguard v4.0 nightly 6 (24)

Configure PT to run as proxy, start local proxy.  For debugging purposes, disabled all PT settings.

In Adguard go to Settings>Network>Proxy and Enable.  PowerTunnel entry is autoconfig:d, check settings anyway and set as http proxy on localhost:9000.  

When Adguard is Disabled, you can go to settings and check connection for the PowerTunnel proxy and it will report connection is successful.  However if you enable Adguard, no internet access.  

I suspect DNS issues and played around with DNS settings in both apps but could not get it to work.

**Comment by krlvm** [comment]
Please, try this:
![image](https://user-images.githubusercontent.com/51774833/96929362-a89cee80-14c2-11eb-998d-e8ff87e313d5.png)

**Comment by krlvm** [comment]
I confirm that works. That happens because AdGuard routes the traffic through PowerTunnel, when the Android system routes the PowerTunnel traffic through AdGuard VPN, and so on ad infinitum.

Write does this solution work for you.

**Comment by krlvm** [comment]
![powertunnel_adguard](https://user-images.githubusercontent.com/51774833/96930414-54930980-14c4-11eb-9767-e4b205a1111d.gif)

**Comment by krlvm** [comment]
Please, write does this solution work for you.

**Comment by n0101** [comment]
D'oh!  I should have thought of that.  Sorry!

**Comment by krlvm** [comment]
> D'oh! I should have thought of that. Sorry!

No worries. Have a good day!
