### ISSUE TITLE
android tv version?

### ISSUE THREAD

**Issue by anditsung** [krlvm/PowerTunnel-Android#4]
hello is it possible to make it useable on netflix on android tv?
the apk for android tv is diffrent from tablet or mobile
on table the apk is com.netflix.mediaclient
but on the android tv is com.netflix.ninja

im able to install the application on the tv
aplication work fine but the app netflix ninja cannot connect to internet if the app is running
but netflix mediaclient works perfectly on the tv

i can use netflix mediaclient but lost remote control function. need to add mouse to control everything.

is it possible to support netflix on tv?

**Comment by krlvm** [comment]
What's the Android TV version?

**Comment by krlvm** [comment]
Unfortunately there is not Netflix for TV for x86 emulator, so I cannot test it.
I suggest you to enable `Only allowed applications` mode in PowerTunnel settings and left the list of apps empty. Then you can go to the your device settings and configure proxy server to `127.0.0.1:8085` - that's underlying PowerTunnel proxy server.

**Comment by anditsung** [comment]
the android tv is using android 8 right now.

when i start the app the network ip become ipv6

tonight will try your solution. 

right now im using mikrotik to forward all netflix connection to vpn to play video.

i dont have any error regarding proxy.
when i test the connection it has error on the server like nw-2-5

**Comment by krlvm** [comment]
> i dont have any error regarding proxy.
> when i test the connection it has error on the server like nw-2-5
Sorry for the misunderstanding: with the PowerTunnel proxy?

> nw-2-5
Is that the Netflix TV error?

**Comment by anditsung** [comment]
when i try to set the proxy manually, the tv will reboot after some time

this is the error on the tv. 

![IMG_2411](https://user-images.githubusercontent.com/1090413/77812789-461f7380-70d6-11ea-8854-7d19835a4144.JPG)

![IMG_2412](https://user-images.githubusercontent.com/1090413/77812785-41f35600-70d6-11ea-8bc3-0df35d07ee0d.JPG)

![IMG_2414](https://user-images.githubusercontent.com/1090413/77812776-399b1b00-70d6-11ea-93cf-19ea7ebfd19c.JPG)

i see you got an update the view on the apps. the view show correctly on android tv

**Comment by krlvm** [comment]
I've managed to get the TV version of the Netflix app on my tablet.
Seems like Netflix TV is using a special protocol (different with the regular Android version), and their server doesn't accept packet that fragmented by PowerTunnel to bypass DPI. I'm sorry.
Reopen this issue if something will change after a while.

**Comment by krlvm** [comment]
I found there are some bugfixes for the traffic interceptor related to packet routing. They probably can fix the issue.
Check [the new version](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.2.1).

**Comment by anditsung** [comment]
try it. still the same.

**Comment by krlvm** [comment]
Unfortunately, apparently, Netflix does not work with fragmented packages. It isn't a PowerTunnel bug.

**Comment by krlvm** [comment]
I discovered a LittleProxy issue (#15) that can be cause of the problem.
This issue could be fixed in an upcoming PowerTunnel version.

**Comment by krlvm** [comment]
Try to check does Netflix TV work with the [latest version](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.5.1)

**Comment by tatunzzz** [comment]
> Try to check does Netflix TV work with the [latest version](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.5.1)

Hi, still got problem connecting on Android TV in Indonesia with TCL TV.

**Comment by krlvm** [comment]
My last assumption is setting chunk size to 0
![Screenshot_1590229111](https://user-images.githubusercontent.com/51774833/82728260-f802a700-9cf7-11ea-9d1e-11377a89ef86.png)

**Comment by ardidjomi** [comment]
I still got problem accesssing Netflix on my android TV box.
