### ISSUE TITLE
Support [ROOT] device with iptables traffic redirection for less battery usage

### ISSUE THREAD

**Issue by hamedsbt** [krlvm/PowerTunnel-Android#41]
Hello, thank you developer for awesome project.
Many advanced users has ROOTED device now-day and it very useful to add ability iptables traffic rule to redirect all traffic through reverse proxy instead VPN mod for less battery usage.
Thank you again!

**Comment by krlvm** [comment]
Have you tried proxy mode in settings?

**Comment by hamedsbt** [comment]
Yes, but may app does not support proxy settings, such as official youtube app.

**Comment by krlvm** [comment]
Can't you configure iptables manually?
(I'm not familiar with it)

**Comment by hamedsbt** [comment]
I'm not very professional iptables user too. it may help: https://tldp.org/HOWTO/TransparentProxy-6.html

**Comment by krlvm** [comment]
I think you can use this, but I haven't tested:
`iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to 127.0.0.1:8085`
To get traffic back execute then:
`iptables -t nat -A POSTROUTING -p tcp -d 192.168.42.10 --dport 80 -j SNAT --to-source 127.0.0.1:8085`

_127.0.0.1:8085_ is the default proxy server address, replace it if you've changed it.

**Comment by hamedsbt** [comment]
Thank you for your try, but I prefer this process handle with app GUI as much as simple and stable.

**Comment by krlvm** [comment]
I don't want to root my device, so I don't think this will be supported in the future.
