### ISSUE TITLE
При включении опции модификации SNI не предлагается установка сертификата.

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel-Android#43]
При включении SNI всего один раз за всё время использования была предложена установка сертификата (узнал об этой возможности вчера). Установку отменил, а повторно вызвать не смог. Даже pm clear приложения не помог. В директории
>/data/data/ru.krlvm.powertunnel.android/files/

лежат файлы

>powertunnel-root-ca.p12
>powertunnel-root-ca.pem
который из них тот самый сертификат ? Попробую поставитьь вручную. Или это не то ?

**Comment by krlvm** [comment]
Как ни странно, я решил эту проблему в версии 1.8, но, видимо из-за недостаточного тестирования, действительно, только что обнаружил, что установщик сертификатов не вызывается даже после переустановки приложения.

Одним из вариантов решения проблемы будет установка [версии 1.7.1](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.7.1), настройка сертификата и последующее обновление до последней версии.

В принципе, если у вас root, то ручная установка сертификата на Android не отличается от таковой на Windows (или любой другой десктопной ОС) - [инструкции по установке](https://github.com/krlvm/PowerTunnel/wiki/SNI-Tricks#step-3-install-powertunnel-root-ca) есть в справке в версии PowerTunnel для PC: переименуйте файл с расширением .pem в файл с расширением .cer и установите его (в следующих версиях, я надеюсь, переименовывать уже ничего не нужно будет).

**Comment by krlvm** [comment]
Промежуточная версия 1.8.3.1 с исправлением:
[PowerTunnel-v1.8.3.1.zip](https://github.com/krlvm/PowerTunnel-Android/files/5708454/PowerTunnel-v1.8.3.1.zip)

**Comment by Baltazar500** [comment]
Сейчас ситуация стала противоположной. В 1.9 опция "Портить SNI" включена по дефолту и сертификат теперь предлагается установить при каждом запуске сервиса, если не переведёшь опцию в состояние "Отключена" перед запуском или пока не установишь сертификат.

**Comment by krlvm** [comment]
> Сейчас ситуация стала противоположной. В 1.9 опция "Портить SNI" включена по дефолту и сертификат теперь предлагается установить при каждом запуске сервиса, если не переведёшь опцию в состояние "Отключена" перед запуском или пока не установишь сертификат.

Сертификат устанавливается раз и навсегда (пока он не будет удален вручную из системного хранилища), пока он установлен в системе - его установка не предлагается. При этом нужно учитывать, что при каждой переустановке/сбросе данных приложения генерируется новый сертификат (старый можно удалить), соответственно, его нужно устанавливать заново.
Что касается "Портить SNI" - кроме названия ничего не поменялось, это и есть та самая опция из предыдущих версий, теперь я лишь добавил еще два варианта модификации SNI. Модификация SNI по умолчанию отключена.
Если сертификат уже был установлен, но его все равно предлагается установить, значит что-то не так с реализацией API хранилища сертификатов производителя устройства.
Я готов добавить опцию для игнорирования этой проблемы, если это действительно так.
Попробуйте сбросить настройки приложения, если вы обновлялись с предыдущих версий.

**Comment by Baltazar500** [comment]
>Модификация SNI по умолчанию отключена.

В том то и дело, что у меня включена. Сертификат пока не установлен. Опция "Портить SNI" врублена по дефолту. Отключаю - запускаю сервис, не отключаю - получаю запрос на установку сертификата. Смахиваю приложение (остановив сервис), опция "Портить SNI" при новом запуске врубается назад, даже если отрубили ранее.

**Comment by krlvm** [comment]
> > Модификация SNI по умолчанию отключена.
> 
> В том то и дело, что у меня включена. Сертификат пока не установлен. Опция "Портить SNI" врублена по дефолту. Отключаю - запускаю сервис, не отключаю - получаю запрос на установку сертификата. Смахиваю приложение (остановив сервис), опция "Портить SNI" при новом запуске врубается назад, даже если отрубили ранее.

Сбросьте настройки приложения (О приложении -> Очистить данные)

**Comment by krlvm** [comment]
**UPD:** действительно есть такой баг, если до обновления модификация SNI была включена - она будет включаться каждый раз при запуске приложения после обновления.

**Comment by Baltazar500** [comment]
>Сбросьте настройки приложения (О приложении -> Очистить данные)

Помогло :)
