### ISSUE TITLE
Главное окно PowerTunnel не влезает целиком на экран

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel-Android#44]
Главное окно PowerTunnel не влезает целиком на экран, приходится постоянно скроллить. Касается это портретного и альбомного режимов.
![2020 12 17_10 49 35](https://user-images.githubusercontent.com/12525093/102424055-0fb7c900-4056-11eb-9904-73b199866358.jpg)
![2020 12 17_10 49 56](https://user-images.githubusercontent.com/12525093/102424071-18100400-4056-11eb-966f-af50f665f81d.jpg)

до кучи, в настройках в портретном режиме не видно опций с длинными заголовками, приходится переворачивать смарт в альюомный режим. Имхо, надо сделать по логн-тапу по опции в портретном режиме подсветку flash-сообщением (или типа того) с полным текстом опции.
![2020 12 17_10 54 48](https://user-images.githubusercontent.com/12525093/102424351-b0a68400-4056-11eb-9d57-1419e25526e9.jpg)

**Comment by krlvm** [comment]
Да, я знаю об этой проблеме, я начал работать над ее решением некоторое время назад и планирую выпустить новую версию до конца декабря.

**Comment by krlvm** [comment]
Я поправил настройки, теперь их возможно читать без лишних проблем на Android 8 и выше.
На счет главного экрана не уверен, кстати, он ведь прокручиваемый? Если так не хочется использовать главный экран, можно вынести ярлычок для включения/выключения PowerTunnel в быстрые настройки, как показано [здесь](https://t.me/powertunnel_dpi/45).

**Comment by Baltazar500** [comment]
>Я поправил настройки, теперь их возможно читать без лишних проблем на Android 8 и выше.

Проблема наблюдалась (и наблюдается) на 4.2.2 и 5.1

**Comment by krlvm** [comment]
> > Я поправил настройки, теперь их возможно читать без лишних проблем на Android 8 и выше.
> 
> Проблема наблюдалась (и наблюдается) на 4.2.2 и 5.1

К сожалению, это распространенная проблема, которая наблюдается во всех (в большинстве) приложений, так как в стандартном API Android отсутствует опция, позволяющая включить перенос строк (хотя начиная с Android 8 уже можно включить перенос описаний настроек, но не названий настроек).
Если есть вопросы, которые касаются самих настроек, то на скриншоте настроек выше на самом деле влез весь текст, единственное, что не влезло целиком - это третья опция снизу - _Отправлять дополнительные 21КБ данных_.

**Comment by Baltazar500** [comment]
>Если есть вопросы, которые касаются самих настроек

Да в принципе вопросов по настройкам нет, раз до андроида 8+ это не выправить. Тут был вопрос больше по основному окну и кнопке "запустить", до которой приходится скроллить.

**Comment by krlvm** [comment]
> > Если есть вопросы, которые касаются самих настроек
> 
> Да в принципе вопросов по настройкам нет, раз до андроида 8+ это не выправить. Тут был вопрос больше по основному окну и кнопке "запустить", до которой приходится скроллить.

Вот с версткой графических интерфейсов у меня к сожалению не очень :(

**Comment by Baltazar500** [comment]
>Вот с версткой графических интерфейсов у меня к сожалению не очень :(

Может на нажатие на лого продублировать функцию кнопки "запустить" ? Или просто поднять её повыше ?

**Comment by krlvm** [comment]
> > Вот с версткой графических интерфейсов у меня к сожалению не очень :(
> 
> Может на нажатие на лого продублировать функцию кнопки "запустить" ? Или просто поднять её повыше ?

Я хочу его на маленьких экранах вообще убрать, остается лишь один вопрос - как определить, влезет ли оно на экран, или нет, потому что все еще зависит и от ширины...
