### ISSUE TITLE
Свободный вход в настройки при активном PT и его автоперезапуск при изменении настроек ?

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel-Android#45]
Провайдер вставил очередные палки и понадобилось мне погонять PT в разных режимах. В итоге это превратилось в муторную задачу - запустить PT, проверить доступ, остановить PT, зайти в настройки, запустить PT ... 

Можно сделать свободный вход при активном PT и его автоперезапуск при изменении настроек, как это реализовано в AdGuard например ?

**Comment by Baltazar500** [comment]
То, что PT перезапускается при выходе из настроек, даже если те не были изменены, это так и задумано ?

**Comment by krlvm** [comment]
Да, все правильно

**Comment by Baltazar500** [comment]
Понятно. Просто я подумал, что если настройки не изменялись, то и перезапуск не нужен ? А то ведь рестарт происходит независимо от изменения настроек.

**Comment by krlvm** [comment]
Нет никакого простого и лаконичного способа узнать, изменились ли настройки, тем более, что в 99% случаев захода в настройки они все-таки будут изменены.
