### ISSUE TITLE
Должен ли моргать светодиод на 4.2.2 при активации режима прокси (не VPN) ?

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel-Android#46]
Ранее я поднимал похожий вопрос, но тогда диод моргал зелёным, да и было это очень похоже на отработку некой функции моргания диодом для VPN-режима, где всё происходило аналогично и в другом софте. Сейчас, на смарте с 4.2.2 он моргает красным и продолжает моргать, пока не дёрнешь панель уведомлений. Когда проводил тесты после очередных палок в колёса от провайдера моргание диодом изрядно набило оскомину, когда пришлось часто перезапускать PT :( На смарте с андроидом 5.1 подобных проблем с диодом нет.

**Comment by krlvm** [comment]
Очень сожалею, но я ничего не могу сделать - эта проблема (если ее возможно считать таковой) относится к ОС Android.

**Comment by krlvm** [comment]
**EDIT:** можно просто целиком отключить уведомления приложения

**Comment by Baltazar500** [comment]
>можно просто целиком отключить уведомления приложения

Отдельной опцией ? Или вообще ? Просто со стороны системы на 4.2.2 long-тап по уведомлению даёт лишь открыть диалог "О приложени", который даёт возможность удалить/остановить приложение и очистить кэш.

**Comment by Baltazar500** [comment]
Наверное всё же нужен тумблер, отключающий уведомление и вместе с ним мигалку-светодиод. Совсем убирать не надо. Имхо.
