### ISSUE TITLE
VPN что-то не работает на LineageOS 14.1 (Android 7.1)

### ISSUE THREAD

**Issue by userkilled** [krlvm/PowerTunnel-Android#49]
Я пытался что-то делать, даже по умолчанию запускать, оно не работало никак, вообще, кроме режима работы, как прокси. Уведомление о попытке запуска VPN даже не поступает. (Версия 1.9 и ниже тоже не работают)
[2021-01-07-21-30-40 (1).txt](https://github.com/krlvm/PowerTunnel-Android/files/5783354/2021-01-07-21-30-40.1.txt)

Если что-то я не понял и сглупил, то прошу меня понять и простить. Если этого лога недостаточно, то я ещё один добавлю, для расшинрения знаний по проблеме.

**Comment by krlvm** [comment]
В самом логе нет никакой ошибки, связанной с VPN, как именно оно не работало (красилось)? Возможно, это не весь лог, так как вы грепали его по имени пакета, в то время как некоторые ошибки приложение выводит в стандартный вывод (System.out/err).
Мне кажется, что приложение скачано с F-Droid, который собирает приложение самостоятельно, попробуйте скачать [отсюда](https://github.com/krlvm/PowerTunnel-Android).

**Comment by userkilled** [comment]
Да, её нет и фильтр применён. Приложение аварийно завершается, если я пытаюсь через шторку бытрого доступа его запустить, только тогда выдны ошибки в MatLog, сейчас так поппробую и отправлю

**Comment by userkilled** [comment]
[2021-01-08-07-56-58 (1).txt](https://github.com/krlvm/PowerTunnel-Android/files/5785300/2021-01-08-07-56-58.1.txt)

**Comment by krlvm** [comment]
Это опять не весь лог, вы грепаете по имени пакета, в то время как код, ответственный за VPN, относится к другому пакету.

**Comment by userkilled** [comment]
Вот лог части системы за некоторый период,
[2021-01-08-09-29-45 (1).txt](https://github.com/krlvm/PowerTunnel-Android/files/5785626/2021-01-08-09-29-45.1.txt)

**Comment by krlvm** [comment]
В логах нет непредвиденной ошибки, скорее всего она обрабатывается и вы должны были получить диалог с ее сообщением.
Данная версия приложения собрана с поддержкой вывода сообщений для отладки, пожалуйста, установите ее и пришлите лог еще раз.
[app-debug.zip](https://github.com/krlvm/PowerTunnel-Android/files/5785736/app-debug.zip)

**Comment by userkilled** [comment]
Ошибку видно, но там пишет "null" Может попробовать реализовать логирование в файл в директории приложения и лишь ссылаться на него, чтобы прочесть, для этого нужен только запрос к памяти, который не запрашивается.
Вот лог, но это снова из MatLog
[2021-01-08-10-33-59 (1).txt](https://github.com/krlvm/PowerTunnel-Android/files/5785816/2021-01-08-10-33-59.1.txt)

**Comment by krlvm** [comment]
Почему-то сведения об отладке не были включены в лог, попробуйте эту версию, в ней вывод сообщений об ошибках в лог не зависит от состояния режима отладки):
[app-debug2.zip](https://github.com/krlvm/PowerTunnel-Android/files/5785894/app-debug2.zip)

**Comment by userkilled** [comment]
Что-то ничего нового не увидел(
[2021-01-08-11-24-08 (1).txt](https://github.com/krlvm/PowerTunnel-Android/files/5786055/2021-01-08-11-24-08.1.txt)
Снова с MatLog

**Comment by krlvm** [comment]
Я предполагаю, что система убивает сервис, либо происходит какая-то ошибка в нативном коде (возможно, связана с модификациями ОС), я добавил для него логирование, попробуйте:
[app-release.zip](https://github.com/krlvm/PowerTunnel-Android/files/5786199/app-release.zip)

**Comment by userkilled** [comment]
В общем, логирования в самой программе после падения нет, но стало больше информации в MatLog:
[2021-01-08-12-13-01 (1).txt](https://github.com/krlvm/PowerTunnel-Android/files/5786291/2021-01-08-12-13-01.1.txt)

**Comment by krlvm** [comment]
> В общем, логирования в самой программе после падения нет, но стало больше информации в MatLog:
> [2021-01-08-12-13-01 (1).txt](https://github.com/krlvm/PowerTunnel-Android/files/5786291/2021-01-08-12-13-01.1.txt)

На самом деле этот лог как раз содержит причину, по которой VPN не работает - VPN соединение не удается установить, предположительно из-за ошибки в системе. Проверьте, есть ли приложение в <Настройки - Подключения - Другие настройки - VPN>. Если есть, то попробуйте [это](https://github.com/krlvm/PowerTunnel-Android/wiki/Troubleshooting-VPN-on-Samsung-devices). В противном случае, проблема может исходить от какого-то модуля Xposed, так как система модифицирована.

**Comment by userkilled** [comment]
Всё перепроверил, ничего не помогает, даже выключение модуля Xposed из Magisk, и все модули в Xposed тоже выключал и его сам из программы, каждый раз перезагружал смартфон. Значит что-то в самой прошивке не то. Попробую на другом устройстве.

**Comment by userkilled** [comment]
Так, проверил, на 5.1.1 работает

**Comment by userkilled** [comment]
Обычные VPN-программы работают, запрашивая доступ туда.

**Comment by userkilled** [comment]
ААААААААААхаххахахахахаха, прикол был в том, что была другая прога постоянной. Поэтому ему было без разницы, что происходит вне постоянной VPN-точки, скорее всего все запросы игнорировались автоматически.
Огромное, Вам, спасибо за терпение и уделённое мне время

**Comment by mikazhen92** [comment]
возможно из-за того, что российские приложения на Android массово внедрили обнаружение впн, новость об этом читал здесь - https://vpnmag.net/rossijskie-prilozheniya-na-android-massovo-vnedrili-obnaruzhenie-vpn/. Возможно и не из-за этого, но я бы проверил все приложения
