### ISSUE TITLE
Не стартует режим VPN на 4.2.2

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel-Android#51]
Собственно решил попробовать для теста VPN на 4.2.2 и словил вот такое :

![2021 01 10_16 11 03~01](https://user-images.githubusercontent.com/12525093/104117075-84360d00-5361-11eb-9995-848f198675ed.jpg)

PT 1.9

**Comment by krlvm** [comment]
А в предыдущих версиях работал?
У меня устройства с 4.x.x нет, поэтому поддержка этих версий "as is", но если это какая-то общая проблема, ее можно исправить.

**Comment by Baltazar500** [comment]
>А в предыдущих версиях работал?

До этого ещё ни разу не врубал PT в режиме VPN на 4.2.2. Могу посмотреть  пару-тройку старых релизов. 

У AdGuard 2.12.250 режим VPN врубается, так что это не общая проблема, а конкретно с PT затык.

**Comment by krlvm** [comment]
Скорее всего и не будут работать, поскольку скорее всего необходимое пространство адресов для локального VPN-сервера недоступно, это можно будет изучить детальнее с выходом новой версии с поддержкой логгирования.

**Comment by Baltazar500** [comment]
Билд 1.5 при включённом VPN сходу крешился, а 1.8.2 выдавал ту же ошибку. Вот что удалось наловить в logcat

```

logcat|grep -iE 'tun2http|vpn'
I/Tun2Http.Service(21562): Waiting for VPN server to start...
I/Tun2Http.Service(21562): MTU=10000
D/Vpn     (  597): setting state=CONNECTING, reason=establish
D/VpnJni  (  597): Address added on tun0: 10.1.10.1/32
E/VpnJni  (  597): Cannot add address: fd00:1:fd00:1:fd00:1:fd00:1/128: Permission denied
D/Vpn     (  597): setting state=FAILED, reason=establish
W/System.err(  597): 	at com.android.server.connectivity.Vpn.jniSetAddresses(Native Method)
W/System.err(  597): 	at com.android.server.connectivity.Vpn.establish(Vpn.java:282)
W/System.err(  597): 	at com.android.server.ConnectivityService.establishVpn(ConnectivityService.java:3783)
E/Tun2Http.Service(21562): Failed to establish VPN: Cannot set address
E/Tun2Http.Service(21562): java.lang.IllegalStateException: Cannot set address
E/Tun2Http.Service(21562): 	at android.os.Parcel.readException(Parcel.java:1433)
E/Tun2Http.Service(21562): 	at android.os.Parcel.readException(Parcel.java:1379)
E/Tun2Http.Service(21562): 	at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1461)
E/Tun2Http.Service(21562): 	at android.net.VpnService$Builder.establish(VpnService.java:472)
E/Tun2Http.Service(21562): 	at tun.proxy.service.Tun2HttpVpnService.start(Tun2HttpVpnService.java:128)
E/Tun2Http.Service(21562): 	at tun.proxy.service.Tun2HttpVpnService.onStartCommand(Tun2HttpVpnService.java:90)
E/Tun2Http.Service(21562): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2850)
E/Tun2Http.Service(21562): 	at android.app.ActivityThread.access$1900(ActivityThread.java:165)
E/Tun2Http.Service(21562): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
E/Tun2Http.Service(21562): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/Tun2Http.Service(21562): 	at android.os.Looper.loop(Looper.java:194)
E/Tun2Http.Service(21562): 	at android.app.ActivityThread.main(ActivityThread.java:5391)
E/Tun2Http.Service(21562): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/Tun2Http.Service(21562): 	at java.lang.reflect.Method.invoke(Method.java:525)
E/Tun2Http.Service(21562): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
E/Tun2Http.Service(21562): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
E/Tun2Http.Service(21562): 	at dalvik.system.NativeStart.main(Native Method)

```

**Comment by Baltazar500** [comment]
похоже проблемы с ipv6 на tun0

**Comment by krlvm** [comment]
Сборка без IPv6: [app-release.zip](https://github.com/krlvm/PowerTunnel-Android/files/5810027/app-release.zip)

**Comment by Baltazar500** [comment]
Заработала :)

![2021 01 14_03 34 46~01](https://user-images.githubusercontent.com/12525093/104489663-3cd6a780-5613-11eb-8744-e21c1310f618.jpg)

Собственно, когда подтвердилось, что проблема в ipv6, я вспомнил про такой твик :

```
echo "1" > '/proc/sys/net/ipv6/conf/all/disable_ipv6'

```

который у меня решает ряд проблем с провайдером на конкретном смарте. Откатил его

```

echo "1" > '/proc/sys/net/ipv6/conf/all/disable_ipv6'

```

и всё завелось на "обычном" релизе :

```
ifconfig ti[Kun0
tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:10.1.10.1  P-t-P:10.1.10.1  Mask:255.255.255.255
          inet6 addr: fd00:1:fd00:1:fd00:1:fd00:1/128 Scope:Global
          UP POINTOPOINT RUNNING  MTU:10000  Metric:1
          RX packets:27 errors:0 dropped:0 overruns:0 frame:0
          TX packets:43 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500 
          RX bytes:5059 (4.9 KiB)  TX bytes:3184 (3.1 KiB)

```

Этот же твик на смарте с 5.1 вызывает тот же эффект (креши или показ попапа), просто там в нём нужды не было ибо проблема специфическая.

**Comment by Baltazar500** [comment]
То, что это не баг понятно, но можно этот момент учесть ? Даже не настройкой, а скорее в коде, если по линии ipv6 идёт отлуп - использовать ipv4 или игнорировать ошибки ipv6 ?

**Comment by krlvm** [comment]
Как видно из логов, причину ошибки невозможно установить непосредственно до инициализации VPN, а текст самой ошибки, доступный для обработки приложением - `Cannot set address` - нельзя трактовать однозначно, поскольку это может быть и ошибка IPv4, тем более что проблема достаточно специфическая.
