### ISSUE TITLE
Лог-файл/лог для локализации проблем ?

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel-Android#52]
Это issue я тоже решил открыть базируясь на вопросах поднятых в соседней ветке, связанными с проблемами открытия сайтов при включённой модификации SNI. 

Ведение лога было бы очень полезно в подобных случаях, имхо. Особенно, если учесть насколько широко позволяет логгировать события десктопная версия.

**Comment by krlvm** [comment]
Начиная с версии 2.0-rc3 после краша будут отображаться подробности и причина проблемы
![Screenshot_20210831_154213](https://user-images.githubusercontent.com/51774833/131505284-3f306ab8-cab3-4d88-9aeb-a5cd31d30b75.jpg)

**Comment by krlvm** [comment]
Полная поддержка просмотра и экспорта логов через приложение доступна в [2.0-rc3](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v2.0-rc3), для этого активируйте соответствующую опцию в настройках, после этого появится пункт в меню трех точек главного экрана. На производительность опция никак не влияет, по умолчанию функция просмотра логов скрыта в косметических целях.
