### ISSUE TITLE
PowerTunnel на 4.2.2 игнорирует сертификат, установленный в системное хранилище

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel-Android#54]
На 4.2.2 я решил пойти по уже проторенной на смарте с 5.1 дорожке и воткнуть сертификат в /system/etc/security/cacerts/ дабы не маяться с пин-кодами, паролями и прочим. Вот только после втыкания сертификата (в списке сертификатов он появился и активен) PT его игнорирует и предлагает установить "пользовательскую" версию. На 5.1 "системный" сертификат без проблем подхватывается.

**Comment by krlvm** [comment]
Обязательную установку сертификата можно будет пропустить в следующей версии (#53).

**Comment by Baltazar500** [comment]
>Обязательную установку сертификата можно будет пропустить в следующей версии

Хорошая новость. Но я несколько о другом. То, что PT предлагал мне установку сертификата при том что он воткнут на уровне системы свидельствовало, что он не был подхвачен :

![2021 01 11_07 37 09~01](https://user-images.githubusercontent.com/12525093/104136165-3dd3c300-53e0-11eb-898f-57761b394b36.jpg)
![2021 01 11_07 36 31~01](https://user-images.githubusercontent.com/12525093/104136159-33b1c480-53e0-11eb-9741-161d570bd08d.jpg)

**Comment by krlvm** [comment]
Все правильно, потому что режим модификации SNI отключается, если сертификат не был найден, API для поиска сертификата на 4.x недоступно.
