### ISSUE TITLE
Shortcut Problem on Android TV

### ISSUE THREAD

**Issue by robin98** [krlvm/PowerTunnel-Android#55]
Hello;
I tried this app on my Android TV(SONY Smart TV), and I noticed there is no any shortcut after installing the app!
You can just run it once after installation using the installation wizard. Also I checked the TV app list from `Settings > Storage` and it was not there neither.

**Comment by krlvm** [comment]
I think I need to create an Android TV launcher icon.
You can use apps like QuickShortcutMaker to launch PowerTunnel for now, but I assume that you should be able to view the list of the apps without the banners.

**Comment by krlvm** [comment]
Try this build, you will see a banner on homescreen (like the Netflix app, etc.):
[app-release.zip](https://github.com/krlvm/PowerTunnel-Android/files/5817112/app-release.zip)

**Comment by robin98** [comment]
@krlvm I tried this build you gave it to me; same problem.
Also tried the QuickShortcutMaker on my android TV and it do nothing for me!

**Comment by krlvm** [comment]
You may try [this](https://play.google.com/store/apps/details?id=eu.chainfire.tv.sideloadlauncher&hl=en&gl=US) app and use it as the default launcher if your device is not very old, if it will not help the issue is definitely with your device either you're doing something wrong.

**Comment by krlvm** [comment]
This version should display TV tile correctly: [PowerTunnel.zip](https://github.com/krlvm/PowerTunnel-Android/files/6479793/PowerTunnel.zip)
