### ISSUE TITLE
How I can install cert with adb command [ROOTED device] ?!

### ISSUE THREAD

**Issue by hamedsbt** [krlvm/PowerTunnel-Android#57]
I've two devices with Android 9 and 10, I cant install cert on android 9 (but installed on Android 10)

I did copy _powertunnel-root-ca.p12_ & _powertunnel-root-ca.pem_ files to /system/etc and issue the command as root shell:
```am start -n com.android.certinstaller/.CertInstallerMain -a android.intent.action.VIEW -t application/x-x509-ca-cert -d file:///system/etc/powertunnel-root-ca.pem``` 
but I got error **"certificate not installed error!"**

**next**: I did copy the powertunnel-root-ca.pem file to ```/system/etc/security/cacerts/ff3efaef.0``` (as my random hash name) but I got error in app:
![image](https://user-images.githubusercontent.com/7298328/105955873-32dd8b80-608c-11eb-95da-3f356588f468.png)

I've ROOT access to my devices, so the question is: 
How I can install it manually with adb and root access?

**Comment by krlvm** [comment]
The Root CA has been assembled incorrectly since you have the file, there's no need in manual certificate installing.
Reset the application data, try again and attach logcat if the error persists.
