### ISSUE TITLE
При переключении режима работы с vpn на прокси при активном режиме vpn, vpn не отключается.

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel-Android#58]
Обнаружил баг.

При переключении режима работы с vpn на прокси при активном режиме vpn, vpn не отключается. Отключить его можно лишь вернув тумблер назад, в режим vpn.

**Comment by krlvm** [comment]
Исправлено в версии [2.0-rc](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v2.0-rc).
Если вы все еще используете старые версии Android, пожалуйста, проверьте, не сломалась ли обратная совместимость.
