### ISSUE TITLE
В режиме vpn параллельно работает прокси PowerTunnel.

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel-Android#59]
Не знаю, баг ли это, но в режиме vpn параллельно работает прокси PowerTunnel при дезактивированном тумблере в настройках. Это видно при запросах через curl.

**Comment by krlvm** [comment]
Так и должно быть, локальный VPN сервер же в свою очередь принимает и перенаправляет пакеты на прокси-сервер.
А вы как хотели?

**Comment by Baltazar500** [comment]
>А вы как хотели?
Ну т.е. я верно понимаю, что запросы с tun0 редиректятся на 127.0.0.1:8085 ? Ну тогда ОК.
