### ISSUE TITLE
More languages 

### ISSUE THREAD

**Issue by sksk6969** [krlvm/PowerTunnel-Android#63]
![Screenshot_20210319-001200_OONI Probe.png](https://user-images.githubusercontent.com/78353984/111657762-16b9c780-884f-11eb-9678-5db1c86f8157.png)

In Korea, there is also a demand for the app due to internet censorship Could you add Korean? If you can't Can you help me to add Korean?

**Comment by krlvm** [comment]
If you want to localize the app, fork the repo and open a Pull Request with localized strings ([the first tutorial from Google](https://code.tutsplus.com/tutorials/how-to-localize-an-android-application--cms-22154)).
But I don't know will you be able to correctly convey the meaning of the settings.
