### ISSUE TITLE
BitTorrent Protocol Support.

### ISSUE THREAD

**Issue by rajsharma91** [krlvm/PowerTunnel-Android#68]
Does PowerTunnel support downloading torrents?

When I'm using PowerTunnel Can ISPs Detect My Torrent Traffic?

**Comment by krlvm** [comment]
I did not test, but **if I remember correctly** you will be able to receive peers list from banned tracker because it serves via HTTP.

**Comment by rajsharma91** [comment]
With PowerTunnel first i tried download & test torrent from here. ( http://checkmyip.torrentprivacy.com )

And it shows my real IP address in both text fields, so it means ISP can detect my torrent traffic.

But in terms of speed, i downloaded KaliLinux torrent (4.3 GB) from official site & PowerTunnel gives me around 80% of speed on my 40 Mbps connection.

**Comment by krlvm** [comment]
PowerTunnel never hides your real IP address, it just bypasses blocking.
