### ISSUE TITLE
Local Ip cannot link

### ISSUE THREAD

**Issue by Khaos116** [krlvm/PowerTunnel-Android#74]
![image](https://user-images.githubusercontent.com/11989916/123654194-0787e400-d858-11eb-9d1d-2ba3cb8d810e.png)
![image](https://user-images.githubusercontent.com/11989916/123654226-1078b580-d858-11eb-83d2-9bcc79027303.png)

**Comment by Khaos116** [comment]
use TunProxy is ok

**Comment by krlvm** [comment]
This is IP address of **PowerTunnel internal proxy server**, not upstream proxy. It should be reset to default values - 127.0.0.1:8080.
**Upstream proxy server** support was added in version 1.9.

**Comment by Khaos116** [comment]
@krlvm Thanks!

**Comment by Khaos116** [comment]
@krlvm 
Is it possible to use "getActivity().onBackPressed()"  instead of "startActivity"?
![image](https://user-images.githubusercontent.com/11989916/123764212-c858a200-d8ee-11eb-93bc-350220af0adf.png)

**Comment by krlvm** [comment]
Which is this activity? I still haven't refactored the tun2http code.

**Comment by Khaos116** [comment]
startActivity will cause multiple activities to be opened，I think it’s better to click the back button

**Comment by krlvm** [comment]
> startActivity will cause multiple activities to be opened，I think it’s better to click the back button

I mean, where did you found it? Multiple activities would not be opened because of MainActivity's SINGLE_TOP flag. I will refactor all this code anyway.

**Comment by Khaos116** [comment]
SettingsFragment and  PackageListPreferenceFragment

**Comment by krlvm** [comment]
This is legacy code from TunProxy. I'm going to rewrite it and improve PackageListPreferenceFragment performance (use RecyclerView) in the next release.

**Comment by Khaos116** [comment]
thank you very much！

**Comment by Khaos116** [comment]
@krlvm  
I found a new problem:
When using Https, you can upstream the data to Charles;
But when using http, it won’t work


I use drony it's ok

**Comment by krlvm** [comment]
Should be a LittleProxy bug, but I can't reproduce

**Comment by Khaos116** [comment]
Okay, let me use Drony for now
Thank you!

**Comment by krlvm** [comment]
You're talking about [this](https://play.google.com/store/apps/details?id=org.sandrob.drony&hl=ru&gl=US) app? If so, then PowerTunnel should not have been used for authorization to the upstream proxy, unnecessary censorship bypass functions in such a scenario degrade performance.

**Comment by Khaos116** [comment]
Yes, I mean this APP.
Because I am a developer, I need to upload data to Charles for easy viewing
