### ISSUE TITLE
Bug Faile to start

### ISSUE THREAD

**Issue by sshnetwork** [krlvm/PowerTunnel-Android#75]
![Screenshot_20210727-001600_PowerTunnel](https://user-images.githubusercontent.com/34721370/127094593-f82845e1-0fc3-41b2-b2c3-b8b8b2b648c0.jpg)

**Comment by krlvm** [comment]
Wrong configuration. I assume you either configured upstream proxy incorrectly, either changed the internal proxy server address to unavailable one. Can you send me your PowerTunnel connection settings?
