### ISSUE TITLE
Не проходят запросы через прокси и vpn на 4.2.2

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel-Android#79]
PT, хлопаться перестал, но далеко "уехать" всё равно не удалось. Прокси работает, но запросы через него ходить не хотят :

>`curl -v -x '127.0.0.1:8085' -skL 'http://www.unit-conversion.info'`
>`*   Trying 127.0.0.1:8085...`
>`* Connected to 127.0.0.1 (127.0.0.1) port 8085 (#0)`
>`> GET http://www.unit-conversion.info/ HTTP/1.1`
>`> Host: www.unit-conversion.info`
>`> User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0`
>`> Accept: */*`
>`> Accept-Encoding: deflate, gzip, br`
>`> Proxy-Connection: Keep-Alive`
>`> `
>`* Empty reply from server`
>`* Connection #0 to host 127.0.0.1 left intact`

Для тестов использовался незаблокированный http - сайт.

upd: С VPN та же петрушка

>`curl -v -skL 'http://www.unit-conversion.info'`
>`*   Trying 23.227.169.89:80...`
>`^C`

**Comment by krlvm** [comment]
Почему-то точно так же не могу открыть любой сайт даже используя какую-нибудь старую версию вроде [1.5](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.5), оно точно работало до этого?

**Comment by Baltazar500** [comment]
>Почему-то точно так же не могу открыть любой сайт даже используя какую-нибудь старую версию вроде 1.5, оно точно работало до этого?

На 1.9 запросы через прокси ходят. Тлько проверил. На 2-й рнвизии на 4.2.2 - глухо.

**Comment by krlvm** [comment]
Проблема такая же, что и в #78, попробуйте:
[PowerTunnel-99jbfix.zip](https://github.com/krlvm/PowerTunnel-Android/files/7109889/PowerTunnel-99jbfix.zip)

Еще я заметил, что режим VPN не работает, поскольку [`addDisallowedApplication`](https://developer.android.com/reference/android/net/VpnService.Builder#addDisallowedApplication(java.lang.String)) на версиях ниже Android 5 не поддерживается, и маршрут зацикливается, у вас он работал когда-либо?

**Comment by Baltazar500** [comment]
>Проблема такая же, что и в #78, попробуйте

Через прокси запросы пошли.

>Еще я заметил, что режим VPN не работает, поскольку addDisallowedApplication на версиях ниже Android 5 не поддерживается, и маршрут зацикливается, у вас он работал когда-либо?\

Я локальными VPN'ами никогда особо не пользовался ибо я тогда не могу маршрутизировать траффик как мне надо. Сейчас погонял ради интереса. 1.9.1 - глухо, PT 2.x, ревизия 97 - глухо, ревизия 99 из аттача выше - глухо.
