### ISSUE TITLE
Doesn't work in android tv

### ISSUE THREAD

**Issue by tommirp** [krlvm/PowerTunnel-Android#8]
I have installed power tunnel apk in android tv (Mi TV) but it doesn't work... Should i setup any options setting?

**Comment by krlvm** [comment]
Are you able to connect to the PowerTunnel VPN Service?
Which is your TV Android version?
Which application are having problems? (I'm aware about Netflix TV issues)

**Comment by kvnwj** [comment]
I have Mi Box S running Android 9 and it worked well for me. It doesn't show the VPN icon on the notification tray, but it's working. It also won't work with the Netflix TV app (com.netflix.ninja) so I decided to sideload regular Netflix app for phones (com.netflix.mediaclient) and it works just fine, you just need some mouse or trackpad and treat the TV screen as a touch screen. :)

**Comment by krlvm** [comment]
> I have Mi Box S running Android 9 and it worked well for me. It doesn't show the VPN icon on the notification tray, but it's working. It also won't work with the Netflix TV app (com.netflix.ninja) so I decided to sideload regular Netflix app for phones (com.netflix.mediaclient) and it works just fine, you just need some mouse or trackpad and treat the TV screen as a touch screen. :)

I'm know about this problem, sideloading regular Android Netflix app is the only solution: Netflix TV doesn't work with fragmented packets. More details in #4, #7.
