### ISSUE TITLE
Missing locale on v2.0

### ISSUE THREAD

**Issue by uaevuon** [krlvm/PowerTunnel-Android#83]
![Screenshot_20210901-170038510](https://user-images.githubusercontent.com/3542715/131635011-ad99f69b-9b4d-4c36-92a2-1e31ea4428bf.jpg)

Please show default language(english) instead of 'missing locale', if strings do not exist that matches current locale.

**Comment by krlvm** [comment]
Thanks for reporting this, it was not intended, the fix is available in [v2.0-rc4](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v2.0-rc4).

**Comment by uaevuon** [comment]
Thank you for your fast response and the fix.
