### ISSUE TITLE
Run proxy without VPN

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel-Android#9]
Доброго времени суток.

Можете запилить режим прокси помимо VPN'а ? Многие браузеры имеют настройки прокси и нет особой нужды включать локальный VPN. Это так же подойдёт для ситуации, когда уже работает софт, использующий локальный режим VPN. В таком случае режим прокси в PowerTunnel + прокси в браузере будет единственной рабочей схемой.

**Comment by krlvm** [comment]
I've added this feature in [version 1.4](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.4).
Go to settings and enable "Proxy mode", then start PowerTunnel as regular and configure proxy server in your apps.

<details>
  <summary>In Russian</summary>
Откройте настройки, включите "Режим прокси", затем запустите PowerTunnel как обычно и настройте прокси-сервер в нужных приложениях.
</details>
