### ISSUE TITLE
How to connect to a proxy (PC-Android)

### ISSUE THREAD

**Issue by SEN5AI** [krlvm/PowerTunnel-Android#94]
I know where to enter what, but in this case I'm stupid. I entered 0.0.0.0 in the application (according to the instructions on the PC Wiki, so that it was available outside the device)
OK, and what address should I enter to connect to it on my computer, being connected via Wi-FI?

**Comment by krlvm** [comment]
You mean, you want to connect to PowerTunnel proxy, which is running on your PC, using Android?

**Comment by SEN5AI** [comment]
> You mean, you want to connect to PowerTunnel proxy, which is running on your PC, using Android?

on the contrary. Power Tunnel works on the phone

**Comment by krlvm** [comment]
You need to determine local IP address of your Android device, on recent Android versions, you can do this by opening Settings -> About -> Status -> IP Address.

**Comment by SEN5AI** [comment]
> You need to determine local IP address of your Android device, on recent Android versions, you can do this by opening Settings -> About -> Status -> IP Address.

OK, I'll try and write the result

**Comment by SEN5AI** [comment]
I figured it out. Your method doesn't work: it specifies the address of the device on the network, but not on the local one.
But I figured out about the proxy. It works by analogy with a router: let's say it has a personal address of 192.168.1.1
, but to get an address for a device that joins it, you need to follow the address rule, for example, by setting 192.168.1.45
It also worked here: I went to the proxy settings in the parameters, entered 0.0.0.1, port 8085 (which is specified in the application) - everything works. But as soon as I entered the address of the device, according to your advice, the Internet "fell".
I will not close the question yet, because it is necessary to confirm the correctness of my shit.

**Comment by krlvm** [comment]
No, it's correct - just tested with my device. The needed IP address is the IP address of the device on the WiFi network to which both the PC and the Android device are connected - `192.168.1.x`. It can be obtained from WiFi router admin page, but it is not available on every router.

The upcoming version will display the private IP address, so you don't need to search for it in settings (don't mind `10.0.2.x`, it's emulator):
![Screenshot_1640529469 (Среднее) (Мелкое)](https://user-images.githubusercontent.com/51774833/147411467-e5019676-8764-4efe-b584-9b4a6e536b98.png)

**Comment by SEN5AI** [comment]
Ok

**Comment by krlvm** [comment]
Here's the APK if you need it now:
[PowerTunnel-99-u2.zip](https://github.com/krlvm/PowerTunnel-Android/files/7777121/PowerTunnel-99-u2.zip)
