### ISSUE TITLE
Any solution to use PowerTunnel with personalDNSfilter

### ISSUE THREAD

**Issue by nkoc6a15** [krlvm/PowerTunnel-Android#98]
Im using InviZible (proxy mode) + pDNSf (VPN mode). Can i use PowerTunnel with that app?

**Comment by krlvm** [comment]
You can run PowerTunnel in proxy mode and specify it as the upstream proxy server in personalDNSfilter if it does support it.
Also, if you need to filter out some hosts, you can install [Firewall](https://github.com/krlvm/PowerTunnel-Firewall) plugin.

**Comment by krlvm** [comment]
Related: #36

**Comment by nkoc6a15** [comment]
> You can run PowerTunnel in proxy mode and specify it as the upstream proxy server in personalDNSfilter if it does support it. Also, if you need to filter out some hosts, you can install [Firewall](https://github.com/krlvm/PowerTunnel-Firewall) plugin.

InviZible in proxy mode and upstream in pDNSf is 127.0.0.1:5354 now

**Comment by krlvm** [comment]
Does InviZible support an upstream proxy?

**Comment by nkoc6a15** [comment]
> Does InviZible support an upstream proxy?

I think no. I use DNSCrypt module in InviZible setup DoH with NextDNS + pDNSf to block ads and tracking and now i want to use PowerTunnel to bypass internet censorship too

**Comment by nkoc6a15** [comment]
PowerTunnel in Proxy mode + addon FoxyProxy in Firefox Android work flawlessly but http3/quic not working

**Comment by krlvm** [comment]
You can set PowerTunnel proxy as the upstream proxy in pDNSf and set InviZible as the upstream proxy in PowerTunnel

**Comment by nkoc6a15** [comment]
You mean set localproxy of PowerTunnel [127.0.0.1]::9000::UDP in pDNSf and set 127.0.0.1:5354 in DNS Resolver in PowerTunnel?

**Comment by krlvm** [comment]
No.

pDNSf (VPN) -> PowerTunnel (Proxy) -> InviZible (proxy)

To set InviZible as a proxy for PowerTunnel, open global PowerTunnel settings

**Comment by nkoc6a15** [comment]
Can you help me with video?

**Comment by nkoc6a15** [comment]
Not working. Setup 127.0.0.1 and port 8085 in proxy settings pDNSf and 127.0.0.1 port 5354 in upstream proxy of PowerTunnel. Can't access to blocked website

**Comment by nkoc6a15** [comment]
Okay its working now. Thank you so much! Quic/http3 still working

**Comment by nkoc6a15** [comment]
Sorry but its not working anymore. Please open it again

**Comment by krlvm** [comment]
Make sure you whitelisted InviZible in pDNSf so the final traffic reaches the destination.

**Comment by nkoc6a15** [comment]
> Make sure you whitelisted InviZible in pDNSf so the final traffic reaches the destination.

I did it already. Its work again. Dont know why. I think its not unstable. Will try again

**Comment by nkoc6a15** [comment]
Look like port 8085 cause it. After change port 8085 to 8080, its looks good now.

**Comment by nkoc6a15** [comment]
Does change port to 8080 will have any cons? I tried port 80 but app crash

**Comment by nkoc6a15** [comment]
Sometimes it works and it didnt work again. Not stable. Changed port to 8080 and still not fixed

**Comment by krlvm** [comment]
Changing the port can't help.

It seems that one of three proxies in the chain is periodically being sent to sleep by Android system. Add all three apps to never-sleep list of OS Settings.

**Comment by nkoc6a15** [comment]
> Changing the port can't help.
> 
> It seems that one of three proxies in the chain is periodically being sent to sleep by Android system. Add all three apps to never-sleep list of OS Settings.

I did it already, seems not working. Im using Redmi Note 10 Pro test with Firefox Android.

**Comment by nkoc6a15** [comment]
![Screenshot_2021-12-29-17-23-25-990_io github krlvm powertunnel android](https://user-images.githubusercontent.com/85343481/147652688-e4cbf802-e1c8-4077-9a55-97f0e5410516.jpg)
![Screenshot_2021-12-29-17-23-08-181_dnsfilter android](https://user-images.githubusercontent.com/85343481/147652696-b9c4fc15-6f83-4785-a53e-0b7462d966c5.jpg)

Here is some screenshot

**Comment by krlvm** [comment]
Do you run InviZible on port 5354? Note that you should run three apps simultaneously to use the Internet connection.

**Comment by nkoc6a15** [comment]
> Do you run InviZible on port 5354? Note that you should run three apps simultaneously to use the Internet connection.

Yes. InviZible port 5354. PowerTunnel 8085. 3 apps running at the same time

**Comment by nkoc6a15** [comment]
Try pDNSf in VPN mode and Proxy (root mode). Sometimes can access blocked website, sometimes cant

**Comment by nkoc6a15** [comment]
I found temporary solution: Using Fennec - access to about:config 
network.proxy.http set to 127.0.0.1
network.proxy.http_port set to 8085
network.proxy.type set to 1

PowerTunnel just need to set to proxy mode. Dont need to enable upstream proxy and change anything in pDNSf or InviZible

Quic/http3 still working

**Comment by krlvm** [comment]
I found a better solution, which removes pDNSf from the chain, but you need to run Android 8 and higher for this.

1) Open pDNSf and enable local DNS proxy instead of VPN in additional settings, it will have IP Address `127.0.0.1:5300`
2) Open PowerTunnel Settings, set it to run as VPN and enable "Strict DNS mode" option
3) Open PowerTunnel Plugins page and enable DNS plugin, set provider to Custom and set DNS IP to `127.0.0.1:5300`
4) In PowerTunnel Settings, set InviZible as upstream proxy server (`127.0.0.1:5354`)
5) Start InviZible, then pDNSf, then PowerTunnel

**Comment by nkoc6a15** [comment]
> I found a better solution, which removes pDNSf from the proxy chain, but you need to run Android 8 and higher for this.
> 
>     1. Open pDNSf and enable local DNS proxy instead of VPN in additional settings, it will have IP Address `127.0.0.1:5300`
> 
>     2. Open PowerTunnel Settings, set it to run as VPN and enable "Strict DNS mode" option
> 
>     3. Open PowerTunnel Plugins page and enable DNS plugin, set provider to Custom and set DNS IP to `127.0.0.1:5300`
> 
>     4. In PowerTunnel Settings, set InviZible as upstream proxy server (`127.0.0.1:5354`)
> 
>     5. Start InviZible, then pDNSf, then PowerTunnel

What about using root mode in pDNSf?

**Comment by krlvm** [comment]
I don't have a rooted device to test.

**Comment by nkoc6a15** [comment]
I though http3/quic cause that. When i use proxy for http and https, its very stable but only http2. Set proxy for only http, http3 go back but not stable when access blocked website

**Comment by nkoc6a15** [comment]
So today i found a solution can use pDNSf + InviZible + PowerTunnel without lose HTTP3/QUIC

**Comment by nkoc6a15** [comment]
InviZible: You need to go to inviZible -> DNSCrypt Settings -> Scroll down below and choose **Edit dnscrypt-proxy.toml directly**

![ảnh](https://user-images.githubusercontent.com/85343481/157903801-f6ddafb1-c7c5-4ee4-90aa-6565550fa8ea.png)

You need to add manually `http_proxy = 'http://127.0.0.1:8085'` because InviZible dont have it before and you need add it below `#proxy = 'socks5://127.0.0.1:9050' ` or InviZible will crash

PowerTunnel: set it into proxy mode and disable DNS plugins

PersonalDNSfilter: Whitelist InviZible and PowerTunnel

Good luck

**Comment by krlvm** [comment]
Thank you!
